name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]  # Specify node versions you'd like to test.

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clear npm cache
        run: npm cache clean --force  # Added step to clean the npm cache

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
