name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy_lambda:  # Fixed typo here (deploye_lamda -> deploy_lambda)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 18]  # Add the node versions you'd like to test across.

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test  # Assuming you want to run tests after installation.
